### ISSUE TITLE
Amxmodx 1.8.2:  [HAMSANDWICH] Failed to retrieve classtype for "", hook for "" not active.

### ISSUE THREAD

**Issue by Stradex** [AoiKagase/Amxx-Laser-TripMine-Entity#1]
While trying to test your mod with amxmodx 1.8.2 (using all the necessary modules), I am getting this error (debug console)

`
L 10/04/2020 - 09:11:12: [HAMSANDWICH] Failed to retrieve classtype for "", hook for "" not active.
L 10/04/2020 - 09:11:12: [AMXX] Displaying debug trace (plugin "lasermine.amxx")
L 10/04/2020 - 09:11:12: [AMXX] Run time error 10: native error (native "RegisterHam")
L 10/04/2020 - 09:11:12: [AMXX]    [0] lasermine.sma::plugin_init (line 141)`

**Comment by AoiKagase** [comment]
Replace lasermine_util.inc and try to compile it again.
