### ISSUE TITLE
plugin

### ISSUE THREAD

**Issue by jokerulty** [AoiKagase/Amxx-Laser-TripMine-Entity#3]
where is the zp cfg? I tried the plugin on my server but i cant change cvars like i want to.
Also i cant bind another key to dellaser only e works that is the default key

**Comment by AoiKagase** [comment]
Rewrite the file name ltm_cvars.cfg to zp_ltm_cvars.cfg and rewrite the in file amx_ltm to zp_ltm.
And the latest version no longer supports the dellaser command; it can only be deleted with the E button.

**Comment by jokerulty** [comment]
I did that and still cvars are not working it doenst change default settings

**Comment by AoiKagase** [comment]
Did you activate this comment at compile time?
```
// #define ZP_SUPPORT
```
